on:
  push:
    branches:
      - deb

env:
  GO_VERSION: 1.15

jobs:
  new-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 3

      - name: Check if version has changed
        run: |
          echo "VERSION_CHANGED=$(git diff --exit-code --ignore-space-at-eol -b -w --ignore-blank-lines HEAD~1 HEAD VERSION)" >> $GITHUB_ENV
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Push a new tag if version has changed
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ env.VERSION }}",
              sha: context.sha
            })
        if: ${{ env.VERSION_CHANGED }}

  build:
    runs-on: ubuntu-latest
    needs: new-tag
    steps:
      - uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get Govv
        run: |
          go get github.com/ahmetb/govvv

      - name: Build
        run: govvv build

      - name: Install fpm
        run: |
          sudo apt-get install ruby ruby-dev rubygems build-essential
          gem install --no-document fpm

      - name: Create deb archive
        run: ./build-deb.sh
