on:
  push:
    branches:
      - master

env:
  GO_VERSION: 1.15

jobs:
  new-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 3

      - name: Check if tag exists
        run: |
          git rev-parse "v$(cat VERSION)" > /dev/null 2>&1
          echo "TAG_MISSING=$?" >> $GITHUB_ENV
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
        shell: bash {0}

      - name: Push a new tag if its missing
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ env.VERSION }}",
              sha: context.sha
            })
        if: ${{ env.TAG_MISSING != 0 }}

  build:
    runs-on: ubuntu-latest
    needs: new-tag
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 # Until https://github.com/actions/checkout/issues/448 gets fixed

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get Govv
        run: |
          go get github.com/ahmetb/govvv

      - name: Build
        run: govvv build

      - name: Install fpm
        run: |
          sudo apt-get install ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm

      - name: Create deb archive
        run: ./build-deb.sh
